(()=>{'use strict';
const TOTAL=11, $=id=>document.getElementById(id),asset=n=>`assets/pages/page-${String(n).padStart(2,'0')}.webp`,pdfPath='assets/Blackout-Fabrics.pdf';
const mobile=()=>matchMedia('(max-width:780px)').matches;let current=1,busy=false,soundOn=true,ac=null,zoom=1,pdfDoc=null,pdfLoading=null,renderTask=null,requestId=0,thumbVisible=false;const spreads=[[0,1],[2,3],[4,5],[6,7],[8,9],[10,11]];const spread=n=>n===1?0:Math.floor(n/2),pair=n=>mobile()?[0,n]:spreads[spread(n)];
function pageHtml(n){return n?`<img alt="หน้า ${n}" src="${asset(n)}" draggable="false">`:`<div class="blank"><div>PROFACE STUDIO</div><b>THE BEAUTY<br>OF THE CURTAIN.</b></div>`}
function setPages(){let [a,b]=pair(current);$('left').innerHTML=pageHtml(a);$('right').innerHTML=pageHtml(b);$('current').textContent=String(current).padStart(2,'0');$('slider').value=current;$('layoutLabel').textContent=mobile()?'แสดงทีละหน้า':'แสดงสองหน้า';$('edgePrev').disabled=$('previous').disabled=$('first').disabled=current===1;$('edgeNext').disabled=$('following').disabled=$('last').disabled=current===TOTAL;document.querySelectorAll('.thumb-item').forEach(x=>x.classList.toggle('selected',+x.dataset.page===current));history.replaceState(null,'',`#page=${current}`)}
function flipSound(){if(!soundOn)return;try{ac=ac||new(window.AudioContext||window.webkitAudioContext)();if(ac.state==='suspended')ac.resume();const time=ac.currentTime,duration=.27,buffer=ac.createBuffer(1,Math.ceil(ac.sampleRate*duration),ac.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<data.length;i++){let v=Math.random()*2-1;data[i]=v*Math.pow(1-i/data.length,2)*.28*(.6+.4*Math.sin(i/data.length*Math.PI))}const source=ac.createBufferSource(),filter=ac.createBiquadFilter(),gain=ac.createGain();filter.type='bandpass';filter.frequency.value=890;filter.Q.value=.75;gain.gain.setValueAtTime(.035,time);gain.gain.exponentialRampToValueAtTime(.0001,time+duration);source.buffer=buffer;source.connect(filter).connect(gain).connect(ac.destination);source.start(time)}catch(e){}}
function go(n,animated=false){n=Math.min(TOTAL,Math.max(1,Number(n)||1));if(busy||current===n)return;let old=current,oldPair=pair(old),nextPair=pair(n),fwd=n>old;let canFlip=animated&&(mobile()?Math.abs(n-old)===1:Math.abs(spread(n)-spread(old))===1);if(!canFlip){current=n;setPages();return}busy=true;flipSound();const f=$('flip');f.style.display='block';f.className=`flip ${fwd?'forward':'backward'}`;
// The turning face displays the previous outer page, with the new inside page on its reverse.
if(mobile()){ $('right').innerHTML=pageHtml(n);$('left').innerHTML='';f.innerHTML=`<div class="face front">${pageHtml(fwd?old:n)}</div><div class="face back">${pageHtml(fwd?n:old)}</div>`; }
else { $('left').innerHTML=pageHtml(nextPair[0]);$('right').innerHTML=pageHtml(nextPair[1]);f.innerHTML=`<div class="face front">${pageHtml(fwd?oldPair[1]:nextPair[1])}</div><div class="face back">${pageHtml(fwd?nextPair[0]:oldPair[0])}</div>`; }
setTimeout(()=>{f.className='flip';f.style.display='none';f.innerHTML='';current=n;busy=false;setPages()},850)}
function step(d){if(mobile())go(current+d,true);else{let idx=spread(current)+d;if(idx>=0&&idx<spreads.length)go(spreads[idx][1],true)}}
$('edgePrev').onclick=$('previous').onclick=()=>step(-1);$('edgeNext').onclick=$('following').onclick=()=>step(1);$('first').onclick=()=>go(1);$('last').onclick=()=>go(TOTAL);$('slider').oninput=e=>go(+e.target.value);$('sound').onclick=()=>{soundOn=!soundOn;$('sound').textContent=soundOn?'♫':'♪̸';$('sound').classList.toggle('active',soundOn);$('sound').title=soundOn?'ปิดเสียงพลิกหน้า':'เปิดเสียงพลิกหน้า'};
let startX=0,startY=0;$('stage').addEventListener('touchstart',e=>{startX=e.touches[0].clientX;startY=e.touches[0].clientY},{passive:true});$('stage').addEventListener('touchend',e=>{let dx=e.changedTouches[0].clientX-startX,dy=e.changedTouches[0].clientY-startY;if(Math.abs(dx)>48&&Math.abs(dx)>Math.abs(dy)*1.2)step(dx<0?1:-1)},{passive:true});
let pointerStart=null;$('book').addEventListener('pointerdown',e=>{if(e.pointerType==='mouse')pointerStart=e.clientX});$('book').addEventListener('pointerup',e=>{if(e.pointerType!=='mouse'||pointerStart===null)return;let delta=e.clientX-pointerStart;pointerStart=null;if(Math.abs(delta)>36)step(delta<0?1:-1);else{let rect=$('book').getBoundingClientRect();step(e.clientX<rect.left+rect.width/2?-1:1)}});
const thumbList=$('thumbList');for(let i=1;i<=TOTAL;i++){let b=document.createElement('button');b.className='thumb-item';b.dataset.page=i;b.innerHTML=`<img src="${asset(i)}" loading="lazy" alt="หน้า ${i}"><span>หน้า ${i}</span>`;b.onclick=()=>{go(i);toggleThumb(false)};thumbList.append(b)}function toggleThumb(flag){thumbVisible=flag===undefined?!thumbVisible:flag;$('thumbs').hidden=!thumbVisible;document.querySelectorAll('.thumb-item').forEach(x=>x.classList.toggle('selected',+x.dataset.page===current))}$('thumb').onclick=()=>toggleThumb();$('closeThumb').onclick=()=>toggleThumb(false);
let toastTimer;function toast(s){$('toast').textContent=s;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),2000)}$('share').onclick=async()=>{try{await navigator.clipboard.writeText(location.href);toast('คัดลอกลิงก์แล้ว')}catch(e){prompt('คัดลอกลิงก์',location.href)}};$('full').onclick=()=>document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen?.().catch(()=>toast('เปิดเต็มหน้าจอไม่สำเร็จ'));
// PDF.js loads only if the user opens high-resolution mode, preserving a fast first load.
// PDF is included locally. If the CDN is unavailable, the native browser PDF renderer is used.
async function getPdf(){if(pdfDoc)return pdfDoc;if(pdfLoading)return pdfLoading;pdfLoading=(async()=>{const lib=await import('https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.10.38/pdf.min.mjs');lib.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.10.38/pdf.worker.min.mjs';return await lib.getDocument({url:pdfPath,cMapPacked:true}).promise})();try{pdfDoc=await pdfLoading;return pdfDoc}catch(err){pdfLoading=null;throw err}}
function fallback(){ $('zoomStatus').hidden=true;$('zoomCanvas').hidden=true;$('pdfFallback').hidden=false;$('pdfFallback').src=`${pdfPath}#page=${current}&zoom=page-fit`;toast('กำลังแสดง PDF ต้นฉบับด้วยโปรแกรมอ่าน PDF ของเบราว์เซอร์')}
async function renderZoom(){let id=++requestId;if($('zoomModal').hidden)return;$('zoomStatus').hidden=false;$('zoomCanvas').hidden=true;$('pdfFallback').hidden=true;$('zScale').textContent=`${Math.round(zoom*100)}%`;try{const doc=await getPdf();if(id!==requestId)return;const page=await doc.getPage(current);if(id!==requestId)return;const body=$('zoomBody'),base=page.getViewport({scale:1}),availableWidth=Math.max(200,body.clientWidth-52),availableHeight=Math.max(250,body.clientHeight-52);let fit=Math.min(availableWidth/base.width,availableHeight/base.height);let pixelScale=Math.min(4,window.devicePixelRatio||1.5);let desired=fit*zoom;const maxPixels=26000000;if(base.width*base.height*(desired*pixelScale)**2>maxPixels)pixelScale=Math.sqrt(maxPixels/(base.width*base.height))/desired;const viewport=page.getViewport({scale:desired*pixelScale});const canvas=$('zoomCanvas');if(renderTask)try{renderTask.cancel()}catch(e){}canvas.width=Math.floor(viewport.width);canvas.height=Math.floor(viewport.height);canvas.style.width=Math.round(base.width*desired)+'px';canvas.style.height=Math.round(base.height*desired)+'px';renderTask=page.render({canvasContext:canvas.getContext('2d',{alpha:false}),viewport});await renderTask.promise;if(id!==requestId)return;canvas.hidden=false;$('zoomStatus').hidden=true;if(zoom===1){body.scrollTo(0,0)} }catch(err){if(err?.name==='RenderingCancelledException')return;console.warn('PDF.js unavailable; native PDF fallback',err);if(id===requestId)fallback()}}
function showZoom(){zoom=1;$('zoomPage').textContent=`หน้า ${current} / ${TOTAL} · PDF QUALITY`;$('zoomModal').hidden=false;document.body.style.overflow='hidden';renderZoom()}
function closeZoom(){$('zoomModal').hidden=true;document.body.style.overflow='';requestId++;if(renderTask)try{renderTask.cancel()}catch(e){}$('pdfFallback').src='about:blank'}
$('magnify').onclick=showZoom;$('zClose').onclick=closeZoom;$('zIn').onclick=()=>{zoom=Math.min(5,+(zoom+.35).toFixed(2));renderZoom()};$('zOut').onclick=()=>{zoom=Math.max(.65,+(zoom-.35).toFixed(2));renderZoom()};$('zFit').onclick=()=>{zoom=1;renderZoom()};$('zoomBody').addEventListener('wheel',e=>{if(e.ctrlKey||e.metaKey){e.preventDefault();zoom=Math.min(5,Math.max(.65,zoom+(e.deltaY<0?.2:-.2)));renderZoom()}},{passive:false});
let resizeTimer;window.addEventListener('resize',()=>{clearTimeout(resizeTimer);resizeTimer=setTimeout(()=>{if(!busy)setPages();if(!$('zoomModal').hidden)renderZoom()},180)});document.addEventListener('keydown',e=>{if(e.key==='Escape'){if(!$('zoomModal').hidden)closeZoom();else toggleThumb(false);return}if(!$('zoomModal').hidden)return;if(['INPUT','TEXTAREA'].includes(document.activeElement?.tagName))return;if(e.key==='ArrowRight')step(1);if(e.key==='ArrowLeft')step(-1)});
let initial=Number(new URLSearchParams(location.hash.slice(1)).get('page'));current=Number.isInteger(initial)&&initial>=1&&initial<=TOTAL?initial:1;setPages();for(let n=2;n<=4;n++){let pre=new Image();pre.src=asset(n)}
})();
